### PR TITLE
fix date picker  onChange

### LINKED ISSUE #1871: Text entry in date filter does not trigger submit
### What went wrong?

When you use the date filter and type a date directly into the text field, then hit <kbd>Enter</kbd>, nothing happens.

### What did you expect to happen?

The expected behaviour would be that the enter key would submit the form. In this case, the query should be updated and results should reload.

### Screenshot

_No response_

### Where did you find the bug?

- [x] https://ianalyzer.hum.uu.nl
- [ ] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [ ] a local server

### Version

5.21.0

### Steps to reproduce

- Go to a corpus with a date filter (I used P&P Netherlands)
- Use the text entry field in the date filter to type a new date
- Hit Enter

### PR DESCRIPTION
**Pull request by lukavdplas**
close #1871

### CODE REVIEW

File: frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.ts [hunk 1]
```diff
@@ -12,30 +13,30 @@ export class DatePickerComponent {
...
-            const dateFormat = this.unit === 'year' ? 'YYYY' : 'DD-MM-YYYY';
-            return parse(value, dateFormat, null, null);
-        } else {
-            return value;
-        }
+    ngOnInit() {
+        this.control.setValue(this.value || this.default);
+        this.control.valueChanges.pipe(
+            takeUntilDestroyed(this.destroyRef)
+        ).subscribe(() => this.onValueChange());
```
Comment (jgonggrijp) [inline frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.ts:33]: I was curious about this PR because you asked me about the `InputEvent`. I find it interesting how you found a more "Angular-native" solution.

Do I understand correctly that you are using the `takeUntilDestroyed` operator to ensure that the subscription closes when the lifespan of the component instance ends—in other words, to prevent a memory leak?

Comment (lukavdplas) [reply frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.ts:33]: Yes, `takeUntilDestroyed` is to close the subscription when the component is destroyed. Actually, it may be superfluous in this case? (Textbook use is when you subscribe to observables that may outlive the component instance, e.g. from a service.)

The `InputEvent` question was not related to this PR, actually. (The context was that I wanted to signal something to a non-angular JS library. Specifically [binding Vega signals to external elements](https://vega.github.io/vega/docs/signals/#binding-directly-to-external-elements).)

Comment (jgonggrijp) [reply frontend/src/app/corpus-selection/corpus-filter/date-picker/date-picker.component.ts:33]: I don't know whether `takeUntilDestroyed` is needed for component-internal observables; that depends entirely on whether the garbage collector in the browser is able to clean up circular references. It's a circular reference because the component holds a reference to the observable, which holds a reference to the subscribing closure, which closes over `this`, which is the component.

In Backbone, a best practice for views (=components) is to call `.remove()` at the end of their lifetime. This cuts off all event listeners, exactly in order to prevent memory leaks by circular references. That makes me think that the circularity might actually be a problem here.

In any case, I found it interesting to learn about `takeUntilDestroyed`.
